name: "Make request to GitHub Glue"
description: "Make request to GitHub Glue"
inputs:
  http_method:
    description: "The HTTP method for the request"
    required: false
    default: "POST"
  json_data:
    description: "JSON body to send in the request"
    required: false
    default: "{}"
  glue_url:
    description: "Glue API Base URL"
    required: true
  glue_api_version:
    description: "Glue API version"
    required: false
    default: "v1"
  glue_project:
    description: "The project in the Glue configuration file"
    required: true
  glue_path:
    description: "The path following the Glue project without a prefix /"
    required: true
runs:
  using: "composite"
  steps:
    - uses: Chia-Network/actions/github/jwt@main

    - name: Make Glue Request
      shell: sh
      run: |
        temp_file=$(mktemp)
        http_status=$(curl -s -o ${temp_file} -w "%{http_code}" -X${{ inputs.http_method }} -H "Authorization: Bearer ${{ env.JWT_TOKEN }}" --data '${{ inputs.json_data }}' ${{ inputs.glue_url }}/api/${{ inputs.glue_api_version }}/${{ inputs.glue_project }}/${{ inputs.glue_path }})
        if [ $http_status -ge 200 ] && [ $http_status -le 299 ]; then
          echo "request successful"
          rm ${temp_file}
        else
          echo "Error: HTTP status code return ${http_status}"
          echo "Message: $(cat ${temp_file})"
          rm ${temp_file}
          exit 1
        fi
