version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "tuesday"
    labels:
      - dependencies
      - github_actions
    target-branch: "main"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
    reviewers:
      - "altendky"
      - "cmmarslender"
