name: "Get library"

description: "Get the library contents"

outputs:
  root:
    description: "The root of the library JSON"
    value: ${{ steps.library.outputs.root }}

runs:
  using: "composite"
  steps:
    - name: Set library output
      id: library
      shell: sh
      run: |
        echo -n "root=" >> "${GITHUB_OUTPUT}"
        cd "${GITHUB_ACTION_PATH}"
        yq -o=json library.yaml > library.json
        cat library.json | tee -a "${GITHUB_OUTPUT}"
