name: "Poetry"
description: "Install Poetry (Python packaging and dependency manager) and run `poetry install`"
inputs:
  python-executable:
    description: "The Python executable used to install and run Poetry."
    required: false
    default: "python"
  poetry-command:
    description: "Poetry command to run. Does install by default."
    required: false
    default: "install"
  poetry-version:
    description: "Version of Poetry to install.  Defaults to latest."
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Confirm Python and Pip are installed
      shell: bash
      run: |
        OUTPUT_TEMP_PATH=$(mktemp)
        if ! ${{ inputs.python-executable }} --version >"${OUTPUT_TEMP_PATH}" 2>&1
        then
          echo "provided python failed to run: ${{ inputs.python-executable }}"
          cat "${OUTPUT_TEMP_PATH}"
          exit 1
        fi

        if ! ${{ inputs.python-executable }} -m pip --version >"${OUTPUT_TEMP_PATH}" 2>&1
        then
          echo "provided python failed to run pip: ${{ inputs.python-executable }}"
          cat "${OUTPUT_TEMP_PATH}"
          exit 1
        fi

    - name: Install Poetry
      shell: bash
      run: |
        if [[ "${{ inputs.poetry-version }}" == "latest" ]]; then
          poetry_version_string=""
        else
          poetry_version_string="==${{ inputs.poetry-version }}"
        fi
        ${{ inputs.python-executable }} -m pip install -I poetry${poetry_version_string}

    - name: Run Poetry command (Linux)
      shell: bash
      run: |
        ${{ inputs.python-executable }} -m poetry ${{ inputs.poetry-command }}
