name: "Poetry"
description: 'Install Poetry (Python packaging and dependency manager) and run `poetry install`'
inputs:
  python-executable:
    description: "The Python executable used to install and run Poetry."
    required: false
    default: 'python'
  poetry-command:
    description: "Poetry command to run. Does install by default."
    required: false
    default: 'install'
runs:
  using: "composite"
  steps:
    - name: Confirm Python and Pip are installed
      shell: bash
      run: |
        OUTPUT_TEMP_PATH=$(mktemp)
        if ! ${{ inputs.python-executable }} --version >"${OUTPUT_TEMP_PATH}" 2>&1
        then
          echo "provided python failed to run: ${{ inputs.python-executable }}"
          cat "${OUTPUT_TEMP_PATH}"
          exit 1
        fi
        
        if ! ${{ inputs.python-executable }} pip --version >"${OUTPUT_TEMP_PATH}" 2>&1
        then
          echo "provided python failed to run pip: ${{ inputs.python-executable }}"
          cat "${OUTPUT_TEMP_PATH}"
          exit 1
        fi

    - name: Install Poetry
      shell: bash
      run: |
        if ! ${{ inputs.python-executable }} -m poetry --help &> /dev/null
        then
          ${{ inputs.python-executable }} -m pip install poetry
        fi

    - name: Run Poetry command (Linux)
      shell: bash
      run: |
        ${{ inputs.python-executable }} -m poetry ${{ inputs.poetry-command }}
