name: "Clean Workspace"
description: "Cleans the current workspace before checking out code, to ensure a clean slate"
runs:
  using: "composite"
  steps:
    - name: Clean Files
      run: |
        # This step needs both sudo and non-sudo versions of the same command in case this is run in a container
        # without sudo installed
        sudo find . -name . -o -prune -exec rm -rf -- {} + || true
        find . -name . -o -prune -exec rm -rf -- {} + || true
        
        sudo rm -rf $HOME/.npm || true
        rm -rf $HOME/.npm || true
      shell: sh
    - name: Clean macOS Keychain
      if: runner.os == 'macOS'
      run: |
        # relevant to https://github.com/Apple-Actions/import-codesign-certs
        security delete-keychain signing_temp.keychain || true
      shell: sh
