name: "Clean Workspace"
description: "Cleans the current workspace before checking out code, to ensure a clean slate"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        pwd
        sudo find . -name . -o -prune -exec echo -- {} + || true
        sudo find . -name . -o -prune -exec rm -rf -- {} + || true
        echo sudo rm -rf $HOME/.npm
        sudo rm -rf $HOME/.npm || true
      shell: sh
