name: "Terraform Apply"
description: "Runs a terraform apply in the given workspace with the given vars file"
inputs:
  workspace:
    description: "The terraform workspace to run in. Usually a region, like us-west-2"
    requied: true
  varfile:
    description: "The vars file to pass to terraform"
    required: true
  terraform_dir:
    description: "Path to terraform directory"
    required: true
runs:
  using: "composite"
  steps:
    - name: Ensure dependencies are present
      run: |
        ( command -v apk && apk add jinja2-cli && ln -s $(which jinja2) $(dirname $(which jinja2))/j2 ) || true
        ( command -v apt-get && apt-get update && apt-get install -y j2cli ) || true
      shell: sh

    - name: Template values
      shell: sh
      working-directory: ${{ inputs.terraform_dir }}
      run: |
        if [ -f "${{ inputs.varfile }}.j2" ]; then
           echo "Var file is .j2 - Processing with j2..."
           j2 "${{ inputs.varfile }}.j2" -o "${{ inputs.varfile }}"
        fi

    - name: Init
      working-directory: ${{ inputs.terraform_dir }}
      run: terraform init
      shell: sh

    - name: Ensure workspace exists
      working-directory: ${{ inputs.terraform_dir }}
      run: |
        terraform workspace new ${{ inputs.workspace }} || true
      shell: sh

    - name: Select Workspace
      working-directory: ${{ inputs.terraform_dir }}
      run: terraform workspace select ${{ inputs.workspace }}
      shell: sh

    - name: Apply
      working-directory: ${{ inputs.terraform_dir }}
      run: terraform apply -auto-approve -var-file=${{ inputs.varfile }}
      shell: sh
