name: "Keep workflow enabled"
description: "Disables and re-enables the running workflow to avoid 60 day CI disables from GitHub for repo inactivity"
inputs:
  repository:
    description: 'The repository the workflow is in'
    required: true
  workflow_id:
    description: 'A single Workflow ID'
    required: true
  access_token:
    description: 'Your GitHub Access Token, defaults to: {{ github.token }}'
    default: '${{ github.token }}'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: apt update && apt install jq -y
      shell: sh
    - name: Flip workflow
      run: |
        curl -X PUT -H "Authorization: token ${{ github.token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow_id }}/disable
        curl -X PUT -H "Authorization: token ${{ github.token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow_id }}/enable
      shell: sh

