name: "Keep workflow enabled"
description: "Disables and re-enables the running workflow to avoid 60 day CI disables from GitHub for repo inactivity"
inputs:
  repository:
    description: 'The repository the workflow is in'
    default: ${{ github.repository }}
    required: true
  workflow_id:
    description: 'A single Workflow ID'
    required: true
  access_token:
    description: 'Your GitHub Access Token, defaults to: {{ github.token }}'
    default: '${{ github.token }}'
    required: true
runs:
  using: "composite"
  steps:
    - name: Flip workflow
      run: |
        echo "[INFO] Flipping workflow for ${{ github.repository }} workflow ID ${GITHUB_ACTION}"
        echo "[INFO] Flipping workflow for ${{ inputs.repository }} workflow ID ${{ inputs.workflow_id }}"
        WORKFLOW_API_ENDPOINT="https://api.github.com/repos/${{ github.repository }}/actions/workflows/${GITHUB_ACTION}"
        curl -sX PUT -H "Authorization: token ${{ github.token }}" -H "Accept: application/vnd.github.v3+json" "$WORKFLOW_API_ENDPOINT/disable"
        curl -sX PUT -H "Authorization: token ${{ github.token }}" -H "Accept: application/vnd.github.v3+json" "$WORKFLOW_API_ENDPOINT/enable"
      shell: sh
