name: "Set up GPG Commit Signing"
description: "Imports a GPG Key and sets up commit signing"
inputs:
  gpg_private_key:
    description: 'GPG private key exported as an ASCII armored version or its base64 encoding'
    required: true
  passphrase:
    description: 'Passphrase of the GPG private key'
    required: false
  working-directory:
    description: "working directory for the commands"
    default: "."
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        # If running as root, then dont use sudo
        if [ "$(id -u)" -eq 0 ]; then
            SUDO=""
        else
            SUDO=$(command -v sudo || echo "")
        fi

        ( command -v apk && ${SUDO} apk add git gpg gpg-agent ) || true
        ( command -v apt-get && ${SUDO} apt-get update && ${SUDO} apt-get install -y git gpg gpg-agent ) || true
      shell: sh
    - name: Call upstream import gpg action
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.gpg_private_key }}
        passphrase: ${{ inputs.passphrase }}
        workdir: ${{ inputs.working-directory }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
