name: "Set up GPG Commit Signing"
description: "Imports a GPG Key and sets up commit signing"
inputs:
  gpg_private_key:
    description: 'GPG private key exported as an ASCII armored version or its base64 encoding'
    required: true
  passphrase:
    description: 'Passphrase of the GPG private key'
    required: false
runs:
  using: "composite"
  steps:
    - name: Call upstream import gpg action
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ inputs.gpg_private_key }}
        passphrase: ${{ inputs.passphrase }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
