name: "Log in to Vault with GitHub JWT"
description: "Log in to Vault with GitHub JWT"
inputs:
  vault_url:
    description: "Full URL including port to vault"
    required: true
  role_name:
    description: "The role name to for login, as named in vault"
    required: true
runs:
  using: "composite"
  steps:
    - uses: Chia-Network/actions/github/jwt@main

    - name: Get credentials from vault
      shell: sh
      run: |
        creds=$(curl -s --request POST -d "{\"jwt\":\"$JWT_TOKEN\",\"role\":\"${{ inputs.role_name }}\"}" ${{ inputs.vault_url }}/v1/auth/github-jwt/login)

        VAULT_TOKEN=$(echo $creds | jq -r '.auth.client_token')
        echo "VAULT_TOKEN=$VAULT_TOKEN" >> $GITHUB_ENV
        echo "::add-mask::$VAULT_TOKEN"
