name: "Cache pip"
description: "Use GitHub Actions cache for pip"

runs:
  using: "composite"
  steps:
    - name: Set pip cache directory environment variable
      id: create-directory
      shell: bash
      run: |
        python "${GITHUB_ACTION_PATH}/cache_pip.py"

    - name: Cache pip
      uses: actions/cache@v4
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MIN: 1
      with:
        path: ${{ steps.create-directory.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Report cache directory contents
      shell: bash
      run: |
        ls -la "${PIP_CACHE_DIR}"
