name: "Cache pip"
description: "Use GitHub Actions cache for pip"

runs:
  using: "composite"
  steps:
    - name: Set pip cache directory environment variable
      id: create-directory
      shell: bash
      run: |
        DIR=$(mktemp -d)
        echo temporary pip cache directory created at: "${DIR}"
        ls -la "${DIR}"
        echo "PIP_CACHE_DIR=${DIR}" >> "$GITHUB_ENV"
        echo "dir=${DIR}" >> "$GITHUB_OUTPUT"

    - name: Cache pip
      uses: actions/cache@v4
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MIN: 1
      with:
        path: ${{ steps.create-directory.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Report cache directory contents
      shell: bash
      run: |
        ls -la "${PIP_CACHE_DIR}"
