name: "Cache pip"
description: "Use GitHub Actions cache for pip"

inputs:
  pre-delete:
    description: "Start by deleting the target directory"
    required: false
    default: "true"
  mode:
    description: "what type of package management is being used"
    type: choice
    default: "setuptools"
    options:
      - "setuptools"
      - "poetry"

runs:
  using: "composite"
  steps:
    - name: Set pip cache directory environment variable
      id: create-directory
      shell: bash
      env:
        PRE_DELETE: ${{ inputs.pre-delete }}
      run: |
        python "${GITHUB_ACTION_PATH}/cache_pip.py" "${{ inputs.mode }}"

    - name: Cache pip
      uses: actions/cache@v5
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MIN: 1
      with:
        path: ${{ steps.create-directory.outputs.dir }}
        key: ${{ runner.os }}-${{ inputs.mode }}-${{ (inputs.mode == 'pip' && hashFiles('**/setup.py')) || (inputs.mode == 'poetry' && hashFiles('**/poetry.lock')) || 'unhandled_case' }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.mode }}-

    - name: Report cache directory contents
      shell: bash
      run: |
        ls -la "${{ steps.create-directory.outputs.dir }}"
