name: "Gets JWT Token from GitHub"
description: "Gets JWT token from github"
runs:
  using: "composite"
  steps:
    - name: Ensure dependencies are present
      shell: sh
      run: |
        ( command -v apk && apk add jq curl curl-dev ) || true
        ( command -v apt-get && apt-get update && apt-get install -y jq curl ) || true

    - name: Get JWT from GitHub
      shell: sh
      run: |
        JWT_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
        echo "::add-mask::$JWT_TOKEN"
        echo "JWT_TOKEN=$JWT_TOKEN" >> $GITHUB_ENV

    - name: Check that token isn't empty
      shell: sh
      run: |
        if [ -z "${{ env.JWT_TOKEN }}" ]; then
            echo "Error: JWT_TOKEN is empty! Ensure `id-token: write` is set in permissions."
            exit 1
        fi
