name: 🚨 Check dependabot config

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
  cancel-in-progress: true

jobs:
  check-dependabot-config:
    name: Check dependabot config
    runs-on: [ubuntu-latest]
    timeout-minutes: 5

    steps:
      - uses: Chia-Network/actions/git-mark-workspace-safe@main

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_COMMIT }}

      - uses: Chia-Network/actions/commit-sign/gpg@main
        with:
          gpg_private_key: ${{ secrets.CHIA_AUTOMATION_PRIVATE_GPG_KEY }}
          passphrase: ${{ secrets.CHIA_AUTOMATION_PRIVATE_GPG_PASSPHRASE }}

      - name: Check dependabot config generation is up to date
        run: |
          ./update-dependabot-config.sh

      - name: Commit any changes back to the repo
        if: always()
        run: |
          ( git commit -am "Updating dependabot configuration" && git push ) || true
