name: test-setup-rust

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.arch.name }} ${{ matrix.environment.name }}
    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix][matrix.environment.matrix] }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: macOS
            matrix: macos
            runs-on:
              arm:
                chia: [macOS, ARM64]
                github: [macos-latest]
              intel:
                github: [macos-13]
          - name: Ubuntu
            matrix: ubuntu
            runs-on:
              arm:
                chia: [Linux, ARM64]
              intel:
                github: [ubuntu-latest]
          - name: Windows
            matrix: windows
            runs-on:
              intel:
                github: [windows-latest]
        arch:
          - name: ARM
            matrix: arm
          - name: Intel
            matrix: intel
        environment:
          - name: Chia
            matrix: chia
            context: self-hosted
          - name: GitHub
            matrix: github
            context: github-hosted
        exclude:
          - os:
              matrix: ubuntu
            arch:
              matrix: arm
            environment:
              matrix: github
          - os:
              matrix: windows
            arch:
              matrix: arm
          - os:
              matrix: windows
            environment:
              matrix: chia
          - arch:
              matrix: intel
            environment:
              matrix: chia

    steps:
      - uses: actions/checkout@v4

      - name: Run the action with toolchain
        uses: ./setup-rust/
        id: with-toolchain
        with:
          path: setup-rust/test/with-toolchain/

      - name: check toolchain is available
        run: |
          cd setup-rust/test/with-toolchain/
          cargo check

      - name: Run the action without toolchain
        uses: ./setup-rust/
        continue-on-error: true
        id: without-toolchain
        with:
          path: setup-rust/test/without-toolchain/

      - name: Make sure unsigned check failed
        if: steps.without-toolchain.outcome != 'failure'
        run: |
          false
