name: test-create-venv

on:
  push:
    branches:
    - main
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.arch.name }} ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
    container: ${{ matrix.os.container[matrix.python.matrix] }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: macOS
            matrix: macos
            runs-on:
              arm: [macOS, ARM64]
              intel: [macos-latest]
          - name: Ubuntu
            matrix: ubuntu
            runs-on:
              arm: [Linux, ARM64]
              intel: [ubuntu-latest]
          - name: Docker Debian
            matrix: docker-debian
            runs-on:
              arm: [Linux, ARM64]
              intel: [ubuntu-latest]
            container:
              'py3.7': docker://python:3.7-bullseye
              'py3.8': docker://python:3.8-bullseye
              'py3.9': docker://python:3.9-bullseye
              'py3.10': docker://python:3.10-bullseye
              'py3.11': docker://python:3.11-bullseye
          - name: Windows
            matrix: windows
            runs-on:
              intel: [windows-latest]
        python:
          - name: '3.7'
            action: '3.7'
            check: '3.7'
            matrix: 'py3.7'
          - name: '3.8'
            action: '3.8'
            check: '3.8'
            matrix: 'py3.8'
          - name: '3.9'
            action: '3.9'
            check: '3.9'
            matrix: 'py3.9'
          - name: '3.10'
            action: '3.10'
            check: '3.10'
            matrix: 'py3.10'
          - name: '3.11'
            action: '3.11'
            check: '3.11'
            matrix: 'py3.11'
        arch:
          - name: ARM
            matrix: arm
          - name: Intel
            matrix: intel
        exclude:
          # Only partial entries are required here by GitHub Actions so generally I
          # only specify the `matrix:` entry.  The super linter complains so for now
          # all entries are included to avoid that.  Reported at
          # https://github.com/rhysd/actionlint/issues/249
          - os:
              name: Windows
              matrix: windows
              runs-on:
                intel: [windows-latest]
            arch:
              name: ARM
              matrix: arm
          - os:
              name: macOS
              matrix: macos
              runs-on:
                arm: [macOS, ARM64]
                intel: [macos-latest]
            python:
              name: '3.7'
              action: '3.7'
              check: '3.7'
              matrix: 'py3.7'
            arch:
              name: ARM
              matrix: arm

    steps:
    - uses: actions/checkout@v3
      with:
        path: repo

    - name: Set up ${{ matrix.python.name }}
      uses: ./repo/setup-python
      with:
        python-version: ${{ matrix.python.action }}

    - name: Run the action
      uses: ./repo/create-venv
      id: create-venv

    - uses: ./repo/activate-venv
      with:
        directories: ${{ steps.create-venv.outputs.activate-venv-directories }}

    - name: Check if Python is from env
      env:
        REFERENCE_PATH: ${{ runner.temp }}
        EXPECTED_INSIDE: true
      run: |
        python3 repo/activate-venv/test_check_activated.py

    - name: Check Python version
      env:
        PYTHON_CHECK: ${{ matrix.python.check }}
      run: |
        python3 repo/setup-python/test_check_version.py
